* What is this?
** The Alberta government, on March 29, 2021, released a draft curriculum for Kindergarten to Grade 6
   Behind the scenes, they have been making small changes.
   This was pointed out with the change below.

   There may have been other changes in the meantime, as the version was bumped from 795 to 799.

   When 795 was archived for this project, not all known files were being accessed.

   In future, more of the changes should be detected.

* Differences Between 799 and 801
** Added
*** Music
    This copy was added to the footer of the printable PDF and as a notice on the music section of the webpage.
**** en-ca
     All works included are illustrative examples only and are not mandatory teaching elements.
**** fr-ca
     Toutes les œuvres incluses ne sont que des exemples illustratifs et ne sont pas des éléments d'enseignement obligatoires.

* Differences Between 795 and 799
** Before
*** Social Studies 6
**** How do Canada and the United States compare in their histories and policies relating to religious and ethnic pluralism?
***** en-ca
      Freedom of religious practice is encouraged, but acceptance comes less easily—in part, because newcomers bring new and unfamiliar religious faiths and practices.
***** fr-ca
      La liberté de pratique religieuse est encouragée, mais l’acceptation est moins facile, en partie parce que les nouveaux arrivants apportent des croyances et des pratiques religieuses nouvelles et peu familières.
** After
*** Social Studies 6
**** How do Canada and the United States compare in their histories and policies relating to religious and ethnic pluralism?
***** en-ca
      Freedom of religious practice is encouraged, but we sadly know from history that acceptance can come less easily—in part, because newcomers bring new and unfamiliar religious faiths and practices. But fear of the unknown can be no excuse for intolerance. Students will specifically study other faith traditions so that unfamiliar practices become respected and understood in a pluralistic society.
***** fr-ca
      La liberté de pratique religieuse est encouragée, mais l’histoire nous apprend malheureusement que l’acceptation est moins facile, en partie parce que les nouveaux arrivants apportent des croyances et des pratiques religieuses nouvelles et peu familières. Mais la peur de l’inconnu ne peut servir d’excuse à l’intolérance. Les élèves examineront d’autres traditions religieuses afin que les pratiques non familières soient respectées et comprises dans une société pluraliste.
